version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "skip issue"
      - "skip news"
    target_branch:
      - "master"
      - "3.9"
      - "3.8"
